### PR TITLE
refactored get_module_name  method

### PR DESCRIPTION
**Pull request by korir248**

### CODE REVIEW

**Review by pando85 — APPROVED** [review]

**Comment by pando85** [comment]
Thank you very much

**Comment by korir248** [comment]
Getting the checks to pass wasn't easy lol

**Comment by pando85** [comment]
Oh, I'm sorry. I appreciate your effort to adapt yourself to my code standards.
LGTM

**Comment by korir248** [comment]
> Oh, I'm sorry. I appreciate your effort to adapt yourself to my code standards. LGTM

No problem. I got to learn something new today!

**Pull request merged**
